name: london-data
channels:
  - conda-forge
dependencies:
  - python=3.9
  - geopandas=0.13.2
  - jupyterlab=4.0 
  - rioxarray
  - rasterstats=0.19
  - matplotlib=3.8
  - numpy=1.23.5
  - openpyxl
  - pandas=2.1.0

